import type { ViuMeta } from "./ViuDocs";

/**
 * Overlay de contenido en INGLÉS del Storybook VIU (default = en).
 *
 * Cada story mantiene su `parameters.viu` en ESPAÑOL como fuente; acá va la traducción al
 * inglés, keyed por el `title` del meta (ej. "Components/Atoms/Badge"). ViuDocs mergea:
 * en locale `en` usa estos campos y cae a español donde falten; en `es` usa la story tal cual.
 * `status`/`figma` no se traducen — salen siempre de la story.
 *
 * Refinable: este texto lo generó Claude fiel al copy español; Natalia lo edita acá, en un
 * solo lugar, sin tocar las stories. (Traducido en lote jul-2026; 74 componentes.)
 */
export const VIU_EN: Record<string, Partial<ViuMeta>> = {
  // ── Atoms ──────────────────────────────────────────────────────────────────
  "Components/Atoms/Avatar": {
    overview: "Representation of a user: image or initials on a brand surface. 5 sizes.",
    whenToUse: ["Identify a person or entity.", "Lists, comments, headers."],
    whenNotToUse: ["For system icons → Icon / Icon container.", "For product logos."],
    anatomy: ["Circular container (radius/pill).", "Image (cover) or initials (1–2)."],
    accessibility: ["The image carries a descriptive alt.", "Initials: contrast guaranteed over brand-2."],
    dos: ["Use initials as the image fallback.", "Size it to match the density."],
    donts: ["Don't put more than 2 initials.", "Don't use images without alt."],
  },
  "Components/Atoms/Badge": {
    overview:
      "Non-interactive status or category label. 6 soft tones (neutral + feedback), light background with on-soft text (AA).",
    whenToUse: [
      "Communicate a categorical state or count (New, Active, 3).",
      "Classify an item alongside it.",
    ],
    whenNotToUse: [
      "If it's actionable → use Pill/Chip.",
      "For notifications over an icon → Notification badge.",
    ],
    anatomy: [
      "Pill container, soft tone (background *-soft + *-on-soft text).",
      "Optional leading icon (@xs, default glyph sell); inherits the text color.",
      "Label in micro-uppercase (Label/S).",
    ],
    accessibility: [
      "Non-interactive; meaning goes in the text, not color alone.",
      "The leading icon is decorative (aria-hidden).",
      "If the state changes live, consider aria-live on the container.",
    ],
    dos: ["Short text (1–2 words).", "Tone consistent with meaning (danger = error)."],
    donts: ["Don't make it clickable.", "Don't rely on color alone."],
  },
  "Components/Atoms/Button": {
    overview:
      "An interface action. Communicates a context's operation and ranks it by variant (primary → secondary → tertiary).",
    whenToUse: [
      "Trigger an action: submit, save, create, confirm.",
      "Rank actions: one primary per view, the rest secondary/tertiary.",
    ],
    whenNotToUse: [
      "To navigate to another page or URL → use Link.",
      "For icon-only actions → use Icon button.",
    ],
    anatomy: [
      "Container — variant (color) + size (height).",
      "Label — General Sans Medium.",
      "Optional icon — leading and/or trailing (16px).",
    ],
    accessibility: [
      "It's a native <button>: focus, Enter and Space work on their own.",
      "Visible focus with a border/focus outline.",
      "Disabled removes interaction and lowers contrast (don't use it to hide critical actions).",
    ],
    dos: [
      "A single primary action per view.",
      "Short, actionable label (one verb).",
      "An icon that reinforces meaning, not decorative.",
    ],
    donts: [
      "Don't use tertiary for the main action.",
      "Don't use long sentences as a label.",
      "Don't combine 3 primary buttons competing.",
    ],
  },
  "Components/Atoms/Checkbox": {
    overview: "Box for multiple or binary selection, with an indeterminate state.",
    whenToUse: ["Turn an option on/off.", "Select several from a list (indeterminate on the parent)."],
    whenNotToUse: ["Single choice among options → use Radio.", "Trigger something instantly → consider Switch."],
    anatomy: ["Box (radius/xs) + check / bar (indeterminate).", "Optional label."],
    accessibility: [
      "Native <input type=checkbox>; associate a label.",
      "Indeterminate is visual (not a third submitted value).",
      "Visible focus.",
    ],
    dos: ["Use indeterminate for “some selected”.", "Make the label clickable."],
    donts: ["Don't use a checkbox for immediate actions."],
  },
  "Components/Atoms/Chip": {
    overview: "Compact chip: removable input, with avatar, or selectable (choice).",
    whenToUse: ["Removable input tokens (input tags, recipients).", "Multiple selection, choice style."],
    whenNotToUse: ["Non-interactive label → Tag/Badge.", "Simple on/off filter → Pill."],
    anatomy: ["Pill container.", "Optional avatar (variant).", "Remove action (✕) or check (choice)."],
    accessibility: ["The remove button carries an aria-label.", "Choice exposes aria-pressed; visible focus."],
    dos: ["Use `onRemove` for removable inputs.", "Choice for multiple selection."],
    donts: ["Don't mix remove and choice in the same chip."],
  },
  "Components/Atoms/Divider": {
    overview: "Horizontal or vertical visual separator, with an optional label.",
    whenToUse: ["Separate groups of content.", "Divide sections (“or”) with a label."],
    whenNotToUse: ["For spacing → use space tokens, not a divider.", "As decoration with no function."],
    anatomy: ["Line (border/default).", "Optional centered label (horizontal)."],
    accessibility: ["Exposes role=separator with orientation.", "Decorative: adds no noise for the screen reader."],
    dos: ["Use it between logical groups."],
    donts: ["Don't use it for padding/spacing."],
  },
  "Components/Atoms/Icon": {
    overview:
      "Icons = Material Symbols (Google). The `glyph` prop accepts the system's legacy names (Plus, Check, Chevron, Close, Arrow, Search, Info, Alert, Visibility, VisibilityOff, Folder) — mapped to Material symbols — or a Material name directly (e.g. `calendar_month`). Color = currentColor; size = font-size.",
    whenToUse: ["Reinforce the meaning of an action or state.", "Inside other components (Button, Input, Tab…)."],
    whenNotToUse: [
      "As the only way to communicate something critical → pair it with text or `title`.",
      "For large illustrations — it's not an illustration system.",
    ],
    anatomy: [
      "Ligature from the «Material Symbols Outlined» font (loaded by the app).",
      "Directional: Chevron→chevron_right, Arrow→arrow_forward (rotated via CSS).",
    ],
    accessibility: [
      "Decorative by default (aria-hidden).",
      "With `title` it's exposed as an image with an accessible name.",
      "Inherits the text color (currentColor).",
    ],
    dos: ["Inherit the color from the context.", "Use `title` when the icon has meaning of its own."],
    donts: ["Don't rescale it and break the 16 grid.", "Don't use icons outside the set without adding them to the system."],
  },
  "Components/Atoms/IconButton": {
    overview: "Square icon-only button. Same hierarchy as Button (primary/secondary/tertiary) in 3 sizes.",
    whenToUse: ["A recognizable action without text (close, search, more).", "Toolbars or areas with limited space."],
    whenNotToUse: ["If the icon isn't unambiguous → use Button with a label.", "For navigation → Link / Nav."],
    anatomy: ["Square container (variant + size).", "Centered icon (16/20/24)."],
    accessibility: [
      "`aria-label` is MANDATORY (there's no visible text).",
      "Visible focus; native Enter/Space.",
      "Add a Tooltip to reveal its function.",
    ],
    dos: ["Always pass `aria-label`.", "Use unambiguous icons."],
    donts: ["Don't leave it without an accessible name.", "Don't use tertiary for the main action."],
  },
  "Components/Atoms/IconContainer": {
    overview:
      "Circular frame for an icon (Figma 574:150). 3 sizes × 8 tones × 2 styles (filled/stroke). The icon color is inherited from the tone.",
    whenToUse: ["Highlight an icon as a featurette (empty states, lists, feedback).", "Give a glyph visual weight and color semantics."],
    whenNotToUse: ["For actions → use Icon button.", "Inline icon in text → Icon."],
    anatomy: ["Circle (radius/pill) with a surface (filled) or a border (stroke).", "Centered icon 16/24/32, colored by the tone."],
    accessibility: [
      "Inherits the semantics of the icon it contains (decorative or titled).",
      "Don't communicate state by tone color ALONE — pair it with the glyph.",
    ],
    dos: ["Choose the tone by its semantics (danger/success/info…).", "Use stroke for a lighter accent."],
    donts: ["Don't make it clickable → that's Icon button."],
  },
  "Components/Atoms/Image": {
    overview: "Media with a fixed aspect ratio and loading/error states. 5 ratios.",
    whenToUse: ["Display images while keeping their proportion.", "Galleries, cards, thumbnails (small ratio)."],
    whenNotToUse: ["Icons → Icon.", "Avatars → Avatar."],
    anatomy: ["Container (radius/control, overflow).", "Default: cover image · Loading: Spinner · Error: icon + “No image”."],
    accessibility: ["Descriptive `alt` (empty if decorative).", "The error state is visible and textual."],
    dos: ["Choose the ratio to match the context.", "Define a meaningful alt."],
    donts: ["Don't distort the image (object-fit cover prevents it)."],
  },
  "Components/Atoms/Input": {
    overview:
      "Single-line text field. Captures short entries (name, email, search) with clear focus, error and disabled states.",
    whenToUse: [
      "Short single-line text entry.",
      "Inside a Form field (label + helper/error) for forms.",
    ],
    whenNotToUse: [
      "Long / multiline text → use Textarea.",
      "Choosing among predefined options → use Select.",
    ],
    anatomy: [
      "Container — bg/subtle + border by state.",
      "Text — value (text/primary) and placeholder (text/tertiary), Body/M.",
      "State — Default · Hover · Focus · Error · Disabled.",
    ],
    accessibility: [
      "It's a native <input>: associate a <label> (or use it inside Form field).",
      "The error state exposes aria-invalid; state the reason in text, not just color.",
      "Visible focus with a border/focus border (2px).",
    ],
    dos: [
      "Always pair it with a visible label.",
      "Use the placeholder as an example, not as a label.",
      "Show the error with text, not just the red border.",
    ],
    donts: [
      "Don't use the placeholder for critical instructions.",
      "Don't disable it without explaining why.",
    ],
  },
  "Components/Atoms/Kbd": {
    overview: "Monospaced keycap to represent a key or keyboard shortcut. Grows with the text from a square minimum.",
    whenToUse: ["Show a shortcut (⌘K, Esc, Enter).", "Document keys in help or menus."],
    whenNotToUse: ["For inline code → use a `<code>`.", "For a clickable action → use Button."],
    anatomy: ["Box (bg/elevated + border/default + radius/control) with a bottom shadow.", "JetBrains Mono text (code/S), text/secondary."],
    accessibility: ["Renders a semantic `<kbd>`.", "The text contrast meets AA."],
    dos: ["Use the real key symbol (⌘, ⇧, ↵).", "Combine several Kbd for a shortcut (⌘ + K)."],
    donts: ["Don't use it as a button.", "Don't put long phrases inside it."],
  },
  "Components/Atoms/Link": {
    overview: "Inline text link to navigate to another page, section or resource.",
    whenToUse: ["Navigate to a URL or anchor.", "A secondary text action within a paragraph."],
    whenNotToUse: ["To trigger an action (submit/save) → use Button.", "As a styled button."],
    anatomy: ["Text (text/link), underlined on hover.", "States: default · hover · disabled · focus."],
    accessibility: ["It's an <a> with href; use descriptive text (not “click here”).", "Visible focus; disabled exposes aria-disabled."],
    dos: ["Text that describes the destination.", "Distinguishable from normal text (color + hover)."],
    donts: ["Don't use Link for actions.", "Don't overuse “read more” without context."],
  },
  "Components/Atoms/NotificationBadge": {
    overview: "Notification indicator over an icon: dot or count (with “99+” overflow).",
    whenToUse: ["Flag new or unread items over an icon/avatar.", "Show a count of pending items."],
    whenNotToUse: ["Content status label → use Badge.", "As a tag or category."],
    anatomy: ["Crimson pill with a bg/base ring.", "Dot or count (with `max`)."],
    accessibility: ["Pair it with accessible text (e.g. “3 unread”).", "Don't communicate through the dot alone."],
    dos: ["Position it over the corner of the icon.", "Use `max` to avoid long numbers."],
    donts: ["Don't put long text in it.", "Don't use it as a content Badge."],
  },
  "Components/Atoms/Pill": {
    overview: "Actionable, selectable filter chip (on/off toggle).",
    whenToUse: ["Quick selectable filters (categories).", "A set of toggle-style options."],
    whenNotToUse: ["For a non-interactive label → use Tag/Badge.", "For removable input → use a Chip input."],
    anatomy: ["Pill container with a border.", "States: default · hover · selected (brand) · disabled · focus."],
    accessibility: ["It's a <button> with aria-pressed.", "Visible focus; Enter/Space."],
    dos: ["Indicate selection with `selected`.", "Group related pills together."],
    donts: ["Don't use it as a static label."],
  },
  "Components/Atoms/Progress": {
    overview: "Determinate (0–100) or indeterminate progress bar. 3 sizes.",
    whenToUse: ["Show measurable progress (loading, % of steps).", "Indeterminate for waits with no known %."],
    whenNotToUse: ["Short waits → Spinner.", "Layout loading → Skeleton."],
    anatomy: ["Track (subtle) + fill (brand).", "Sizes sm/md/lg."],
    accessibility: ["role=progressbar with aria-valuenow/min/max.", "Pass an accessible `label`."],
    dos: ["Use a real `value` when you know it."],
    donts: ["Don't use indeterminate if you have the %."],
  },
  "Components/Atoms/Radio": {
    overview: "Option button to choose ONE among several mutually exclusive options.",
    whenToUse: ["A single choice among 2–5 visible options.", "Grouped by the same `name`."],
    whenNotToUse: ["Multiple selection → use Checkbox.", "Many options → use Select."],
    anatomy: ["Circle (radius/pill) + inner dot.", "Optional label."],
    accessibility: ["<input type=radio> with a shared name; arrow keys to navigate.", "Visible focus."],
    dos: ["Group them with the same name.", "Always show a default option."],
    donts: ["Don't use loose radios without a group."],
  },
  "Components/Atoms/Rating": {
    overview: "Star rating (0–5), read-only or interactive.",
    whenToUse: ["Show or capture a rating.", "Reviews, surveys."],
    whenNotToUse: ["For progress → Progress.", "For choosing options → Radio."],
    anatomy: ["N stars; filled (brand) vs empty (strong)."],
    accessibility: ["Read-only: role=img with a “X of N” label.", "Interactive: buttons with aria-pressed (keyboard supported)."],
    dos: ["State the maximum.", "Allow keyboard use in interactive mode."],
    donts: ["Don't use half stars without real support."],
  },
  "Components/Atoms/Select": {
    overview: "Picks one option from a short list, with a chevron.",
    whenToUse: ["Choose 1 among several predefined options (5–15).", "Save space compared to radios."],
    whenNotToUse: ["2–4 visible options → use Radio.", "Search/autocomplete → Combobox (future)."],
    anatomy: ["Input-style container + chevron.", "Native options (<option>)."],
    accessibility: ["Native <select>; associate a label.", "Full keyboard support provided by the browser."],
    dos: ["Order the options logically.", "Include a default option."],
    donts: ["Don't use it for multiple selection."],
  },
  "Components/Atoms/Skeleton": {
    overview: "Loading placeholder that anticipates the shape of the content. text/rect/circle.",
    whenToUse: ["Loading structured content (cards, lists).", "Avoid layout shifts."],
    whenNotToUse: ["Very short waits → a Spinner is enough.", "For measurable progress → Progress."],
    anatomy: ["Block with a strong surface + shimmer.", "Variants: text · rect · circle."],
    accessibility: ["Decorative (aria-hidden).", "Respects prefers-reduced-motion (no shimmer)."],
    dos: ["Mimic the shape and proportions of the real content."],
    donts: ["Don't leave it running forever if loading failed (show an error)."],
  },
  "Components/Atoms/Slider": {
    overview: "Selects a value within a continuous range. Single mode (one value) or Range mode (dual thumbs, band between the ends).",
    whenToUse: ["Approximate values in a range (volume, brightness).", "When the adjustment matters more than the exact value.", "Range: filter between a minimum and a maximum (price, dates)."],
    whenNotToUse: ["A precise value → use a numeric Input.", "A few discrete options → Radio/Select."],
    anatomy: ["Track (subtle) + fill/band (brand) + thumb (18px).", "Range: two thumbs over the track; the brand band covers the selected interval."],
    accessibility: ["Native <input type=range>: arrow keys, Home/End.", "Visible focus on the thumb.", "Range: each thumb is an input with its own aria-label (min/max)."],
    dos: ["Show the current value near the slider.", "Define clear min/max/step."],
    donts: ["Don't use it for critical exact values."],
  },
  "Components/Atoms/Spinner": {
    overview: "Indeterminate loading indicator. 3 sizes.",
    whenToUse: ["Short waits with no known progress.", "Inside buttons or areas that are loading."],
    whenNotToUse: ["If there's measurable progress → use Progress.", "For waits with layout → use Skeleton."],
    anatomy: ["Ring with a spinning brand arc."],
    accessibility: ["Exposes role=status with an aria-label.", "Respects prefers-reduced-motion (spins slower)."],
    dos: ["Pair it with status text if the wait is long."],
    donts: ["Don't use it for waits with known progress."],
  },
  "Components/Atoms/Status": {
    overview: "Presence/availability indicator: online, busy, away, offline.",
    whenToUse: ["Show a user's or service's presence.", "Next to an Avatar or name."],
    whenNotToUse: ["For process feedback → use Badge/feedback.", "For progress → Progress."],
    anatomy: ["Colored dot (8px).", "Optional label (Label/S)."],
    accessibility: ["The dot exposes an aria-label with the state.", "Don't communicate through color alone: show the label when it matters."],
    dos: ["Show the label when color isn't enough.", "Consistent colors (online = success)."],
    donts: ["Don't rely on the dot alone in critical contexts."],
  },
  "Components/Atoms/Step": {
    overview: "A single step in a sequential process: complete, current, or upcoming.",
    whenToUse: ["Show progress through a step flow (wizard, checkout).", "Compose several into a Stepper."],
    whenNotToUse: ["To switch views → use Tab.", "For continuous progress → Progress."],
    anatomy: ["Node (number or check) + label + connector."],
    accessibility: ["Communicate the state with text/icon, not color alone.", "The number indicates the order."],
    dos: ["Clearly mark the current step.", "Connector between steps."],
    donts: ["Don't use Step for free navigation."],
  },
  "Components/Atoms/Switch": {
    overview: "On/off toggle for a setting that takes effect immediately.",
    whenToUse: ["Turn a setting on/off instantly (no “save”).", "Binary settings."],
    whenNotToUse: ["If it needs to confirm/save → use Checkbox.", "To choose among options → Radio/Tabs."],
    anatomy: ["Track (off = strong / on = brand) + thumb.", "Optional label."],
    accessibility: ["role=switch with aria-checked.", "Visible focus; Enter/Space."],
    dos: ["Apply the change instantly.", "A label that describes the setting."],
    donts: ["Don't use it inside a form that requires submit."],
  },
  "Components/Atoms/Tab": {
    overview: "A single tab for navigating between views. Line or segmented style.",
    whenToUse: ["Switch between views in the same context.", "Group several into a Tabs (molecule)."],
    whenNotToUse: ["For navigation between pages → use Nav.", "For filters → Pill."],
    anatomy: ["Label + optional icon.", "Indicator: underline (line) or fill (segmented)."],
    accessibility: ["role=tab with aria-selected.", "In a group: role=tablist + arrow keys (provided by Tabs)."],
    dos: ["Mark the active one with `active`.", "Few tabs, short labels."],
    donts: ["Don't use tabs for sequential steps → use Stepper."],
  },
  "Components/Atoms/Tag": {
    overview: "Non-interactive classification label. 3 tones (neutral/brand/indigo).",
    whenToUse: ["Classify or label content (categories, topics).", "Show an item's metadata."],
    whenNotToUse: ["If it can be removed or selected → use Chip.", "For feedback status → use Badge."],
    anatomy: ["radius/control container, tone (subtle + text)."],
    accessibility: ["Non-interactive; the meaning comes from the text."],
    dos: ["Use it for stable taxonomy.", "Concise text."],
    donts: ["Don't add actions (✕) → that's Chip."],
  },
  "Components/Atoms/Textarea": {
    overview: "Multiline text field with focus, error, and disabled states.",
    whenToUse: ["Long inputs (comments, descriptions).", "When the content can contain line breaks."],
    whenNotToUse: ["Short single-line text → use Input.", "Predefined options → Select."],
    anatomy: ["Container (bg/subtle + border by state), vertical resize.", "Body/M text."],
    accessibility: ["Native <textarea>; associate a label.", "Error exposes aria-invalid + the reason text."],
    dos: ["Set an appropriate initial number of rows.", "Allow resizing if it helps."],
    donts: ["Don't use it for a single line."],
  },
  "Components/Atoms/Tooltip": {
    overview: "Floating label with brief info on hover/focus of the trigger. Flips to the opposite side if the preferred one falls outside the viewport.",
    whenToUse: ["Clarify an ambiguous icon or action.", "Show the name of a compact control."],
    whenNotToUse: ["For essential content → make it visible.", "For interactive or long content → use Popover."],
    anatomy: ["Bubble (bg/elevated + text), 4 sides.", "Flip at the viewport edge (side → opposite)."],
    accessibility: ["Appears on hover AND focus (keyboard).", "role=tooltip; never put critical info only here."],
    dos: ["Very short text.", "Make sure it appears with the keyboard."],
    donts: ["Don't put actions inside.", "Don't use it for essential info."],
  },

  // ── Molecules ──────────────────────────────────────────────────────────────
  "Components/Molecules/Accordion": {
    overview: "Groups collapsible sections (AccordionItem) separated by dividers.",
    whenToUse: ["FAQs or long content split into sections.", "Reduce scrolling by showing only the essentials."],
    whenNotToUse: ["A few sections that stay visible → show them open.", "Switching between views → use Tabs."],
    anatomy: ["A list of AccordionItem with dividers between them."],
    accessibility: ["Each item: a header with aria-expanded and a body as a region (aria-controls)."],
    dos: ["Clear, scannable titles."],
    donts: ["Don't nest accordions excessively."],
  },
  "Components/Molecules/AccordionItem": {
    overview: "A single collapsible section: a header with title + chevron and a body shown on expand.",
    whenToUse: ["A single collapsible unit of content.", "Compose an Accordion."],
    whenNotToUse: ["Content that must stay visible at all times."],
    anatomy: ["Header (button) with title + chevron that rotates.", "Body (region) shown on expand."],
    accessibility: ["aria-expanded on the header; body as a region with aria-controls.", "Controlled (open/onOpenChange) or uncontrolled (defaultOpen)."],
    dos: ["A title that summarizes the content."],
    donts: ["Don't put long forms inside without need."],
  },
  "Components/Molecules/AvatarGroup": {
    overview: "A set of overlapping avatars representing a group of people, with a +N summary.",
    whenToUse: ["Show participants/collaborators of something.", "Summarize many users in little space."],
    whenNotToUse: ["A single user → use Avatar.", "A detailed listing → use List with avatars."],
    anatomy: ["Overlapping avatars with a ring (bg/base).", "A +N chip when the maximum is exceeded."],
    accessibility: ["Each avatar carries alt/initials; the +N exposes an aria-label with the rest."],
    dos: ["Cap with `max` and show +N.", "Same size for all."],
    donts: ["Don't overlap so much that avatars can't be told apart."],
  },
  "Components/Molecules/Banner": {
    overview: "A persistent contextual message within the layout. 5 tones, with optional action and dismiss.",
    whenToUse: ["Communicate a system or page state (info, error, success).", "Notices that stay until the user acts."],
    whenNotToUse: ["Transient notifications → use Toast.", "Field validation → use FormField/error."],
    anatomy: ["Icon per tone.", "Title (optional) + message.", "Optional inline link + dismiss (optional)."],
    accessibility: ["role=status; the icon is decorative (tone isn't the only signal — use clear text).", "The dismiss has an aria-label."],
    dos: ["Text that explains what happened and what to do.", "A tone that matches the meaning."],
    donts: ["Don't use it for ephemeral messages.", "Don't rely on tone color alone."],
  },
  "Components/Molecules/Breadcrumb": {
    overview: "The hierarchical navigation path to the current page, with a chevron or slash separator.",
    whenToUse: ["Show the location within a hierarchy.", "Let users go back to higher levels."],
    whenNotToUse: ["Primary navigation → use Nav.", "Steps in a process → use Stepper."],
    anatomy: ["A list of levels (links).", "Separators (› or /).", "The current level (unlinked, aria-current)."],
    accessibility: ["nav with aria-label “Breadcrumb”.", "The current item uses aria-current=page; separators are aria-hidden."],
    dos: ["The last item is the current page (no link).", "Keep labels short."],
    donts: ["Don't include too many levels.", "Don't link the current item."],
  },
  "Components/Molecules/ChoiceGroup": {
    overview: "A labeled group of related options. `type=radio` for single selection, `type=checkbox` for multiple. Reuses the Radio and Checkbox atoms.",
    whenToUse: ["Pick one (radio) or several (checkbox) options from a short, visible list.", "When it helps to see all options at once."],
    whenNotToUse: ["Many options → use Select.", "Switching between views → Segmented control / Tabs.", "A single on/off option → a standalone Checkbox or Switch."],
    anatomy: ["Legend (Label/M) — the group label.", "Items — Radio or Checkbox (Body/M) stacked.", "Optional helper (Body/S, text/tertiary)."],
    accessibility: ["fieldset + legend group the controls.", "Radio: arrow-key navigation; the name groups them.", "The helper is associated via aria-describedby."],
    dos: ["Label the group with a clear legend.", "Order options predictably."],
    donts: ["Don't mix radio and checkbox in the same group.", "Don't use a group for a single option."],
  },
  "Components/Molecules/Combobox": {
    overview: "A search field that opens and filters a list to pick one option. Reuses Search (field) and MenuItem (options).",
    whenToUse: ["Pick one of many values by typing (country, user, tag).", "When a plain Select is awkward due to the number of options."],
    whenNotToUse: ["A few fixed options → use Select.", "Multiple selection → consider chips + a custom Combobox.", "Actions (not data) → use Menu."],
    anatomy: ["Field (Search) with a search icon.", "Panel (bg/elevated + shadow/overlay) with options (MenuItem).", "The active option highlighted (bg/hover)."],
    accessibility: ["WAI-ARIA combobox + listbox pattern: focus stays on the input.", "Arrows move the active option (aria-activedescendant), Enter selects, Esc closes.", "aria-expanded reflects the panel state."],
    dos: ["Show a clear empty state when there are no matches.", "Order options predictably."],
    donts: ["Don't use it for 2–3 options.", "Don't hide a critical selection behind the filter."],
  },
  "Components/Molecules/DateRangePicker": {
    overview: "Two fields (From / To) that open a range calendar: endpoints in a brand circle, in-between days in a brand-subtle band. Selection in two clicks.",
    whenToUse: ["Pick a period (reports, bookings, date filters).", "When both start and end matter."],
    whenNotToUse: ["A single date → use Datepicker.", "Relative ranges (last 7 days) → offer presets."],
    anatomy: ["From/To fields (label + Datepicker-style trigger).", "Calendar: header with month + navigation, weekday row (M–S), grid.", "Endpoints = bg/brand circle; in-between = bg/brand-subtle band."],
    accessibility: ["Each field is a button with an aria-label and aria-expanded.", "The calendar is a dialog; Esc closes it; clicking outside does too.", "Each day is a button with the date as its accessible name and aria-pressed on the endpoints."],
    dos: ["Show the selected range in the fields.", "Let users navigate months with the arrows."],
    donts: ["Don't use a range for a single date.", "Don't hide the end day behind too many steps."],
  },
  "Components/Molecules/Datepicker": {
    overview: "A date field with a brand-native calendar: a trigger that opens a popover with the month grid. The selected day is a brand circle and today is a bordered circle.",
    whenToUse: ["Capture a single date.", "Filters or forms with dates."],
    whenNotToUse: ["A date range → DateRangePicker.", "Free text → Input."],
    anatomy: ["Label.", "Field (value or placeholder DD / MM / YYYY + chevron) on bg/subtle.", "Calendar popover: header with month and navigation, weekday row, grid.", "Helper or error."],
    accessibility: ["The trigger exposes aria-haspopup=dialog and aria-expanded.", "Each day is a button with the date as its aria-label and aria-pressed for the selected one.", "Escape closes; a click outside closes. The error uses aria-invalid + text."],
    dos: ["Preselect a sensible date when it applies.", "Use the label and helper with the format."],
    donts: ["Don't parse dates with a free-text Input.", "Don't use the browser's native picker (it breaks the brand)."],
  },
  "Components/Molecules/Dropzone": {
    overview: "An area to upload files by dragging or clicking, with default/active/error states.",
    whenToUse: ["File uploads (images, documents).", "When drag & drop adds value."],
    whenNotToUse: ["Uploading a single simple file → a button may suffice.", "Inputs that aren't files."],
    anatomy: ["Dashed border + icon in a circle.", "Main text + hint (types/limit).", "States: default, active (drag), error."],
    accessibility: ["Operable by keyboard (Enter/Space open the file browser).", "The error is shown as text; describe formats and limits."],
    dos: ["State formats and maximum size.", "Show feedback while dragging."],
    donts: ["Don't hide the limits until it fails."],
  },
  "Components/Molecules/FileRow": {
    overview: "A row for a file being uploaded: type, name and state (uploading with progress, complete, or error).",
    whenToUse: ["List uploaded or in-progress files (alongside a Dropzone).", "Show progress and result per file."],
    whenNotToUse: ["Generic content lists → use List/ListItem."],
    anatomy: ["Type tile (e.g. PDF).", "Name + state: progress / meta / error+retry.", "Remove (✕); check when complete."],
    accessibility: ["Remove/retry buttons with text/aria-label.", "The error is communicated with text, not color alone."],
    dos: ["Show real progress while uploading.", "Offer retry on error."],
    donts: ["Don't leave the row uploading indefinitely after a failure."],
  },
  "Components/Molecules/FormField": {
    overview: "A form wrapper: associates a label (and required) with a control, plus helper or error text.",
    whenToUse: ["Any form control (Input, Select, Textarea…).", "To show contextual help or the reason for an error."],
    whenNotToUse: ["Controls without a visible label (e.g. toolbar) → use aria-label directly.", "To group several fields → a fieldset/section."],
    anatomy: ["Label (+ asterisk if required).", "Control (children).", "Message: helper (tertiary) or error (danger)."],
    accessibility: ["Pass `htmlFor` and the same `id` to the control to associate the label.", "The error is communicated with text, not color alone (mark the control with `error`)."],
    dos: ["Connect label and control with htmlFor/id.", "Show the error as a message, in addition to the border."],
    donts: ["Don't use the placeholder as a label.", "Don't leave controls without a label."],
  },
  "Components/Molecules/List": {
    overview: "A vertical container of rows (ListItem): avatar/icon, title, subtitle, meta and chevron.",
    whenToUse: ["Listings of people, files, results.", "Selectable or navigable rows."],
    whenNotToUse: ["Tabular data with columns → use Table.", "Navigation → use Nav."],
    anatomy: ["<ul role=list> with several ListItem.", "Item: leading + title/subtitle + meta/chevron."],
    accessibility: ["Interactive rows are buttons (keyboard).", "The selected one exposes aria-current."],
    dos: ["Truncate long titles.", "Make the whole row interactive if it's navigable."],
    donts: ["Don't use List for data with many columns."],
  },
  "Components/Molecules/ListItem": {
    overview: "A row in a list: main content (title/subtitle) with optional leading and trailing.",
    whenToUse: ["Each item of a List.", "Rows with avatar/icon, meta and chevron."],
    whenNotToUse: ["Cells of a table → use Table row."],
    anatomy: ["Leading (avatar/icon).", "Title + subtitle.", "Trailing: meta + chevron.", "States: default/hover/selected/disabled."],
    accessibility: ["If navigable, the row is a button (Enter/Space).", "The selected one exposes aria-current."],
    dos: ["Truncate long text with ellipsis."],
    donts: ["Don't put too many elements in the trailing."],
  },
  "Components/Molecules/Menu": {
    overview: "A floating surface with a list of actions (MenuItem). Positioning is handled by the consumer.",
    whenToUse: ["Contextual actions from a trigger (a “more” button, right-click).", "Quick commands."],
    whenNotToUse: ["Selecting a form value → use Select.", "Persistent navigation → use Nav."],
    anatomy: ["Elevated surface (bg/elevated + border/subtle + overlay shadow).", "MenuItem: optional icon + label + shortcut."],
    accessibility: ["role=menu + items role=menuitem.", "Ideally: trapped focus and arrow keys to move (provided by the trigger/popover)."],
    dos: ["Group related actions.", "Show shortcuts when they exist."],
    donts: ["Don't put long forms in a menu."],
  },
  "Components/Molecules/MenuItem": {
    overview: "A single action within a Menu: optional icon, label and keyboard shortcut.",
    whenToUse: ["Each command of a Menu."],
    whenNotToUse: ["As a primary button → use Button.", "An option of a Select → use <option>."],
    anatomy: ["Icon (optional) + label (Body/M) + shortcut (Body/S) or a check when selected.", "States: default/hover/selected/disabled."],
    accessibility: ["role=menuitem; Enter/Space activate it.", "The shortcut is shown as a hint (register it at the app level too)."],
    dos: ["Clear, short verbs.", "Show the shortcut if it exists."],
    donts: ["Don't mix navigation destinations with actions without distinguishing them."],
  },
  "Components/Molecules/Nav": {
    overview: "Vertical navigation landmark. Groups multiple NavItems (with icon, label, and active state).",
    whenToUse: ["Side navigation for an app or section.", "Persistent lists of destinations."],
    whenNotToUse: ["Switching views within a single panel → use Tabs.", "Hierarchical path → use Breadcrumb."],
    anatomy: ["<nav> with aria-label.", "NavItem: icon + label, active state (aria-current)."],
    accessibility: ["Pass an aria-label to the Nav.", "The active item uses aria-current=page."],
    dos: ["Mark the current destination.", "Consistent, optional icons."],
    donts: ["Don't mix actions (buttons) with destinations without distinguishing them."],
  },
  "Components/Molecules/NavItem": {
    overview: "Individual navigation item: icon + label, with default/hover/active states.",
    whenToUse: ["Each destination within a Nav."],
    whenNotToUse: ["As an action button → use Button/Icon button."],
    anatomy: ["Icon (20px) + label (Body/M).", "Active state: brand-2-subtle background + primary text."],
    accessibility: ["It's an <a>; the active one uses aria-current=page.", "Visible focus."],
    dos: ["Clear destination text.", "An icon that helps recognize it."],
    donts: ["Don't use NavItem for actions."],
  },
  "Components/Molecules/Pagination": {
    overview: "Control for moving through pages of a result set. Numbered (with ellipsis) or simple.",
    whenToUse: ["Split long lists/tables into pages.", "When the total number of pages is known."],
    whenNotToUse: ["Continuous loading → use infinite scroll / \"load more\".", "Few items → show them all."],
    anatomy: ["Previous/next buttons.", "Page cells (current highlighted) + ellipsis.", "Simple variant: \"Page X of Y\"."],
    accessibility: ["nav with aria-label; the current page uses aria-current=page.", "Buttons with aria-label (previous/next); disabled at the ends."],
    dos: ["Highlight the current page.", "Disable previous/next at the limits."],
    donts: ["Don't hide the total if you know it.", "Don't use cells too small for the finger."],
  },
  "Components/Molecules/PasswordInput": {
    overview: "Password field with a button to show/hide the value (Visibility / VisibilityOff).",
    whenToUse: ["Capture passwords or other sensitive data.", "Inside a FormField in sign-in forms."],
    whenNotToUse: ["Plain text → use Input.", "One-time codes → consider a segmented input."],
    anatomy: ["Input (same states as Input).", "Visibility/VisibilityOff toggle on the right."],
    accessibility: ["The toggle exposes aria-pressed and changes its aria-label (show/hide).", "Associate a label via FormField; errors use aria-invalid + text."],
    dos: ["Allow showing the password to reduce errors.", "Communicate requirements with helper text."],
    donts: ["Don't block pasting.", "Don't show the password by default."],
  },
  "Components/Molecules/Quote": {
    overview: "Highlighted quotation with an accent line and optional attribution.",
    whenToUse: ["Highlight a testimonial or quote.", "Give voice to an author within content."],
    whenNotToUse: ["System messages → use Banner.", "Running text → use RichText."],
    anatomy: ["Accent line (brand).", "Quote text (Body/XL).", "Attribution: author · source."],
    accessibility: ["Uses semantic <figure>/<blockquote>/<figcaption>."],
    dos: ["Attribute the quote where appropriate."],
    donts: ["Don't overuse long quotes."],
  },
  "Components/Molecules/RichText": {
    overview: "Prose container that applies the VIU type scale to rich content (headings, paragraphs, lists, links).",
    whenToUse: ["Editorial or help content with formatting.", "Render already-converted HTML/Markdown."],
    whenNotToUse: ["Simple UI text → use the viu-type-* classes.", "A single quote → use Quote."],
    anatomy: ["Styles for h2/h3, p, a, ul/ol, blockquote, code, hr."],
    accessibility: ["Use a correct heading hierarchy.", "If you pass `html`, sanitize it first (avoid XSS)."],
    dos: ["Keep the heading hierarchy.", "Sanitize source HTML."],
    donts: ["Don't inject unsanitized HTML."],
  },
  "Components/Molecules/Search": {
    overview: "Search field: input with a magnifier icon and a clear button.",
    whenToUse: ["Search/filter within a view or list.", "As a prominent search entry point."],
    whenNotToUse: ["Generic text entry → use Input.", "Category filters → use Pills."],
    anatomy: ["Search icon (leading).", "Input (pill radius).", "Clear button (when there's a value)."],
    accessibility: ["role=searchbox; associate a label or aria-label.", "The clear button has an aria-label."],
    dos: ["Show the clear button when there's text.", "Debounce the query if it filters live."],
    donts: ["Don't use Search for inputs that aren't search."],
  },
  "Components/Molecules/SegmentedControl": {
    overview: "Single-selection control among mutually exclusive options, with the active segment raised. It's not navigation (that's Tabs).",
    whenToUse: ["Switch between views/modes of the same content (list/grid, day/week/month).", "2–4 short, mutually exclusive options."],
    whenNotToUse: ["Navigate between sections → use Tabs.", "Many options or long labels → use Select.", "Multiple selection → use Choice group (checkbox)."],
    anatomy: ["Track (bg/raised + radius/control).", "Segments (Label/M); the active one is a bg/elevated thumb with shadow/raised.", "Active text text/primary, inactive text/secondary."],
    accessibility: ["role=radiogroup over native radios: arrows move and select.", "Visible focus on the active segment.", "Pass an aria-label to the group."],
    dos: ["Labels of 1–2 words.", "Keep a stable width across options."],
    donts: ["Don't use it for actions (it's not a button group).", "Don't mix it with navigation."],
  },
  "Components/Molecules/Stepper": {
    overview: "Progress through a sequence of steps (composes Step), with connectors between them.",
    whenToUse: ["Linear multi-step flows (onboarding, checkout, wizard).", "Show where you are and how much is left."],
    whenNotToUse: ["Switching views → use Tabs.", "Continuous progress → use Progress."],
    anatomy: ["Multiple Steps (complete/current/upcoming).", "Connectors between steps (the last one has none)."],
    accessibility: ["Communicate state with number/icon and text, not color alone.", "The current step must be clear."],
    dos: ["Clearly mark the current step.", "Few steps, short labels."],
    donts: ["Don't use Stepper for free navigation."],
  },
  "Components/Molecules/TableRow": {
    overview: "A table row: optional selection, content cells, and chevron, with hover/selected states.",
    whenToUse: ["Tabular data with columns (people, records).", "Tables with per-row selection."],
    whenNotToUse: ["Content lists without columns → use List/ListItem."],
    anatomy: ["Selection checkbox (optional).", "Content cells.", "Chevron (optional).", "States: default/hover/selected."],
    accessibility: ["role=row with role=cell; the selected one exposes aria-selected.", "The checkbox has an aria-label and doesn't propagate the row click."],
    dos: ["Align columns with the table header.", "Make the row interactive if it's navigable."],
    donts: ["Don't use TableRow for lists without a column structure."],
  },
  "Components/Molecules/Tabs": {
    overview: "Group of tabs (Tab) with keyboard navigation, in line or segmented style.",
    whenToUse: ["Switch between views of the same context.", "Sections of the same page/panel."],
    whenNotToUse: ["Navigation between pages → use Nav.", "Sequential steps → use Stepper."],
    anatomy: ["role=tablist with several Tabs.", "Active indicator (underline or segmented fill)."],
    accessibility: ["Roving tabindex + ←/→ arrows to move.", "aria-selected on the active one; pass an aria-label to the group.", "Connect each tab with its panel (aria-controls) in your layout."],
    dos: ["Keep few tabs with short labels.", "Remember the active tab per context."],
    donts: ["Don't use Tabs for sequential flows."],
  },
  "Components/Molecules/TimePicker": {
    overview: "Time field with a branded dropdown (Figma 409:6, Open state). Replaces the native picker: a list of times by `step` (default 30 min); the chosen option is marked with bg/subtle + text/primary + check Icon.",
    whenToUse: ["Capture a time.", "Alongside a Datepicker for date + time."],
    whenNotToUse: ["Free text → use Input.", "Duration/range → a dedicated control."],
    anatomy: ["Label.", "Control (value + chevron ↑ when open) over bg/subtle.", "Options dropdown (chosen option with check).", "Helper or error."],
    accessibility: ["Control with aria-haspopup=listbox + aria-expanded; options role=option with aria-selected.", "Keyboard: ↑/↓ move, Enter selects, Escape closes.", "Label associated via htmlFor; error with aria-invalid + text."],
    dos: ["Tune `step`/`min`/`max` to the case.", "Preselect a reasonable time."],
    donts: ["Don't use the browser's native picker (breaks the brand).", "Don't parse time with a free-text Input."],
  },
  "Components/Molecules/Toast": {
    overview: "Transient, floating notification that confirms an action or reports an event. 4 tones.",
    whenToUse: ["Confirm an action (saved, sent).", "Brief notices that auto-dismiss."],
    whenNotToUse: ["Persistent messages in the layout → use Banner.", "Form errors → FormField/error."],
    anatomy: ["Icon per tone (20px).", "Message (+ optional title).", "Close button.", "Elevated surface with overlay shadow."],
    accessibility: ["role=status + aria-live=polite to announce it without stealing focus.", "The close button has an aria-label; keep the text short."],
    dos: ["Brief, actionable text.", "Auto-dismiss after a few seconds (except errors)."],
    donts: ["Don't put long or critical content in it.", "Don't stack too many at once."],
  },
  "Components/Molecules/Toolbar": {
    overview: "Horizontal grouping of actions (Icon button / Button), with optional dividers.",
    whenToUse: ["Action bars for an editor or view.", "Group related controls."],
    whenNotToUse: ["Navigation between views → use Tabs.", "Contextual menu → use Menu."],
    anatomy: ["Surface (bg/raised + border/subtle).", "Actions + vertical Divider to separate groups."],
    accessibility: ["role=toolbar with aria-label; arrow navigation recommended for long sets."],
    dos: ["Group related actions and separate with dividers.", "Use Tooltips on icon buttons."],
    donts: ["Don't mix too many actions without grouping."],
  },
  "Components/Molecules/TreeItem": {
    overview: "A node in a hierarchical tree: expand/collapse chevron (or spacer on a leaf), optional icon and checkbox, per-level indentation, and states.",
    whenToUse: ["Hierarchical structures (folders, categories).", "Compose a TreeView."],
    whenNotToUse: ["Flat lists → use List/ListItem.", "Primary navigation → use Nav."],
    anatomy: ["[Checkbox] + Chevron (or spacer on a leaf) + [Icon] + Label.", "Indentation by `level`."],
    accessibility: ["role=treeitem with aria-expanded/aria-selected/aria-level/aria-disabled.", "Goes inside a role=tree container (TreeView)."],
    dos: ["Indent according to level.", "Mark the selected one.", "Use a checkbox for multiple selection."],
    donts: ["Don't use TreeItem standalone without a role=tree container."],
  },
  "Components/Molecules/VideoEmbed": {
    overview: "Embedded player with a poster and a play button (16:9). On play, load the real player.",
    whenToUse: ["Show a video with a poster before playing.", "Defer loading the heavy player until play."],
    whenNotToUse: ["Images → use Image.", "Audio → a dedicated audio control."],
    anatomy: ["Poster (cover) over a strong surface.", "Centered play button (overlay)."],
    accessibility: ["Play is a <button> with an aria-label.", "Define a descriptive alt for the poster; the real player must have accessible controls."],
    dos: ["Load the real player only when play is pressed.", "A poster representative of the content."],
    donts: ["Don't autoplay with sound.", "Don't use VideoEmbed for static images."],
  },

  // ── Organisms ──────────────────────────────────────────────────────────────
  "Components/Organisms/Card": {
    overview: "Content surface with a full anatomy: media, badge, accent bar, icon, tags, header (eyebrow/title/subtitle + action), body, link, footer (1–2 buttons) and author block. 3 surfaces × 3 layouts × states. Use the controls to show/hide each part.",
    whenToUse: ["Group related content into a single unit (article, project, resource).", "Scannable content grids.", "Selectable cards (Selected state)."],
    whenNotToUse: ["Dense lists → use List.", "Full-page content → doesn't need a Card."],
    anatomy: [
      "Media (optional) + floating Badge + accent bar.",
      "Icon (decoupled 48×48 box) + Tags.",
      "Header: eyebrow + title + subtitle, with an action on the right.",
      "Body + Link ('Read more').",
      "Footer: primary and/or secondary button.",
      "Author: avatar + name + meta, after a divider.",
    ],
    accessibility: [
      "With `interactive`/`onClick`, the card is keyboard-operable (Enter/Space) and shows focus.",
      "Selected uses a brand-2 surface + border (color + signifier, not color alone).",
      "Images carry alt text.",
    ],
    dos: ["One primary action per card.", "Clear hierarchy: eyebrow → title → body."],
    donts: ["Don't add competing elements.", "Don't nest interactive controls when the whole card is clickable."],
  },
  "Components/Organisms/Drawer": {
    overview: "Side panel that slides in from the edge over a scrim. Traps focus and closes with Esc or a click on the backdrop. For flows and content longer than a Modal.",
    whenToUse: [
      "Edit or create with a medium-sized form.",
      "Show detail or filters without leaving the background view.",
      "Multi-field flows that don't warrant a full page.",
    ],
    whenNotToUse: [
      "Short confirmations → use Modal.",
      "Contextual action anchored to a control → use Popover.",
      "Non-blocking messages → use Toast/Banner.",
    ],
    anatomy: [
      "Scrim — alpha/black-72, z/modal layer.",
      "Panel — bg/elevated + shadow/overlay, full height, 420px.",
      "Header — title (Title/M) + close button.",
      "Dividers — border/subtle separating header / body / footer.",
      "Body — scrollable content (gap space/md).",
      "Footer — actions aligned to the right.",
    ],
    accessibility: [
      "role=dialog + aria-modal; aria-labelledby on the title.",
      "Focus trapped while open; Tab/Shift+Tab cycle within.",
      "Esc closes; focus returns to the trigger.",
      "The close button has an aria-label; the scrim closes on click.",
    ],
    dos: ["Title that names the task.", "Persistent actions in the footer (save / cancel).", "Allow the body to scroll without losing the header/footer."],
    donts: ["Don't put multi-step flows in without visible progress.", "Don't remove the exit (Esc + close + scrim).", "Don't use it for ephemeral messages."],
  },
  "Components/Organisms/EmptyState": {
    overview: "Empty state with an icon, title, description and actions. Variants: first use, no results, error.",
    whenToUse: ["First time with no data (onboarding).", "Search/filter with no results.", "Error while loading."],
    whenNotToUse: ["Loading in progress → use Skeleton/Spinner."],
    anatomy: ["Icon in a circle (tint per variant).", "Title + description.", "Actions (primary + secondary)."],
    accessibility: ["The icon is decorative; the message explains the situation in text.", "Offer a clear action to move forward."],
    dos: ["Text that explains what happened and what to do.", "One obvious primary action."],
    donts: ["Don't leave the state without an exit.", "Don't use an error tone for normal empties."],
  },
  "Components/Organisms/Footer": {
    overview: "Page footer with links and a copyright notice, separated by a top border.",
    whenToUse: ["Close a page with secondary and legal links."],
    whenNotToUse: ["Form actions → use an action bar."],
    anatomy: ["Top border.", "Links (children).", "Copyright (fine print)."],
    accessibility: ["Use <footer>; links with descriptive text."],
    dos: ["Group links by topic when there are many."],
    donts: ["Don't put critical actions in the footer."],
  },
  "Components/Organisms/Modal": {
    overview: "Modal dialog centered over a scrim. Traps focus, closes with Esc or a click on the backdrop, and returns focus to the trigger on close.",
    whenToUse: [
      "Confirm an important or destructive action.",
      "Ask for a decision or a short input without leaving the context.",
      "Show focused content that needs full attention.",
    ],
    whenNotToUse: [
      "Non-blocking messages → use Toast or Banner.",
      "Long or content-heavy tasks → use Drawer or a page.",
      "Contextual action anchored to a control → use Popover.",
    ],
    anatomy: [
      "Scrim — alpha/black-72, z/modal layer.",
      "Dialog — bg/elevated + border/subtle + shadow/overlay + radius/surface.",
      "Header — optional icon + title (Title/M) + optional subtitle + close button.",
      "Body — content (Body/M), scrolls if it exceeds the height.",
      "Footer — actions aligned to the right (secondary + primary).",
    ],
    accessibility: [
      "role=dialog + aria-modal; aria-labelledby on the title and aria-describedby on the subtitle.",
      "Focus trapped while open; Tab/Shift+Tab cycle within.",
      "Esc closes; focus returns to the element that opened it.",
      "The close button has an aria-label; the scrim is clickable to close.",
    ],
    dos: ["Clear title that names the action.", "One obvious primary action; secondary to cancel.", "Keep content brief and focused."],
    donts: ["Don't nest modals.", "Don't use it for lengthy content (prefer Drawer/page).", "Don't remove the exit (always Esc + close)."],
  },
  "Components/Organisms/PageHeader": {
    overview: "Page header: breadcrumb, title (+ back/status), subtitle, actions and tabs. 3 variants.",
    whenToUse: ["Head a view or section.", "Give context + the page's primary actions."],
    whenNotToUse: ["Side navigation → use Nav.", "A card's header → no."],
    anatomy: ["Breadcrumb + title (+ back, status).", "Subtitle.", "Actions (right).", "Tabs + divider."],
    accessibility: ["Use <header> with an <h1>.", "Back is an IconButton with an aria-label."],
    dos: ["One clear primary action.", "Breadcrumb when there's a hierarchy."],
    donts: ["Don't add too many actions.", "Don't use more than one h1 per page."],
  },
  "Components/Organisms/Popover": {
    overview: "Floating surface anchored to a trigger, with a caret. For brief contextual content and actions. Closes with Esc, a click outside or the close button.",
    whenToUse: [
      "Show detail or contextual controls next to a button.",
      "Lightweight confirmations or quick in-place adjustments.",
      "Saved filters, secondary options, contextual help.",
    ],
    whenNotToUse: [
      "Blocking or critical decisions → use Modal.",
      "Long forms → use Drawer.",
      "A menu's list of actions → use Menu.",
      "Descriptive text on hover only → use Tooltip.",
    ],
    anatomy: [
      "Trigger — the anchored control (trigger slot).",
      "Surface — bg/elevated + shadow/overlay + radius/surface, z/popover layer.",
      "Caret — points at the trigger per Position (Bottom/Top); flips to the opposite side if it doesn't fit the viewport.",
      "Optional header — title (Label/L) + close button.",
      "Body — text or content (Body/M).",
      "Optional actions — SM buttons aligned to the right.",
    ],
    accessibility: [
      "role=dialog; aria-labelledby on the title when present.",
      "Focus enters the surface on open and returns to the trigger on close.",
      "Esc closes; a click outside the anchor + surface also closes.",
      "The close button has an aria-label.",
    ],
    dos: ["Anchor the surface to the control that spawns it.", "Brief, actionable content.", "Choose Position based on available space."],
    donts: ["Don't put long flows or many fields in it.", "Don't use it for global system messages.", "Don't overdo actions; one primary is enough."],
  },
  "Components/Organisms/Table": {
    overview: "Tabular container: column header + rows (TableRow), with dividers.",
    whenToUse: ["Data in comparable columns.", "Listings with sorting/selection."],
    whenNotToUse: ["Content without columns → use List."],
    anatomy: ["role=table.", "Header (column titles).", "rowgroup with TableRow."],
    accessibility: ["Consistent role=table/row/cell.", "Align header and cells."],
    dos: ["Keep column widths consistent."],
    donts: ["Don't use Table for layout."],
  },
  "Components/Organisms/TreeView": {
    overview: "Hierarchical tree container. Composes TreeItem with indentation, expand/collapse, selection and, optionally, a checkbox/icon per node.",
    whenToUse: ["Explore hierarchies (projects, files, categories).", "Multiple selection in a tree (with checkboxes)."],
    whenNotToUse: ["Flat lists → use List.", "Primary navigation → use Nav."],
    anatomy: ["role=tree with several TreeItem (role=treeitem).", "Each node with children shows a chevron (Expanded/Collapsed); leaves don't.", "Optional: checkbox and/or icon per node."],
    accessibility: ["role=tree + aria-label; items expose aria-expanded/aria-selected/aria-level.", "Keyboard navigation between nodes."],
    dos: ["Indent by level.", "Mark the selected node.", "Use checkboxes for multiple selection."],
    donts: ["Don't nest too deep without collapsing."],
  },

  // ── Patterns ───────────────────────────────────────────────────────────────
  "Components/Patterns/App shell": {
    overview: "Application frame: persistent side navigation + top bar framing a scrollable content area. The shell doesn't change on navigation; only the content changes.",
    whenToUse: [
      "Productivity/desktop apps with several sections and sustained work on large screens.",
      "When first-level navigation must always be visible.",
    ],
    whenNotToUse: [
      "Marketing sites or single-step flows.",
      "Mobile-first experiences → nav goes at the bottom or in a menu/Drawer.",
    ],
    anatomy: [
      "Sidebar — brand, first-level navigation and account. Persistent; marks where the user is. bg/raised + border/subtle.",
      "Topbar — location (breadcrumb), search, primary action and account/notifications.",
      "Content area — page header + each view's own content (KPIs, tables, forms). It's the only thing that changes.",
    ],
    accessibility: [
      "Side navigation is a <nav aria-label> landmark; the active section uses aria-current.",
      "Main content goes in <main>; the shell in semantic regions (aside/header/main).",
      "Logical tab order: sidebar → topbar → content.",
    ],
    dos: [
      "One active section at a time.",
      "Keep the shell persistent; change only the content area.",
      "Keep the primary action always accessible at the top.",
    ],
    donts: [
      "Don't multiply global actions in the topbar.",
      "Don't bake each view's content into the shell as fixed markup.",
      "On small screens, don't keep the side nav fixed: collapse to icons or a Drawer.",
    ],
  },
  "Components/Patterns/Data table": {
    overview: "Data table pattern: toolbar (search/filters/actions) + table with selectable rows + footer (count + pagination). For exploring and managing many records.",
    whenToUse: [
      "Explore/manage many records with comparable metadata — projects, users, transactions.",
      "When multiple selection, sorting and pagination are needed.",
    ],
    whenNotToUse: [
      "Few visual items → use cards (Card).",
      "A single record → use a detail view.",
    ],
    anatomy: [
      "Toolbar — search, filters and primary action.",
      "Table — column headers (sortable) + checkbox selection.",
      "Footer — count (“1–5 of 42”) + pagination.",
      "States — loading (Skeleton), empty (EmptyState inside the body) and error.",
    ],
    accessibility: [
      "The table uses a role/landmark with an aria-label; clear column headers.",
      "Accessible checkbox selection; state is conveyed with text, not color alone.",
      "The empty state keeps the toolbar and header to preserve context.",
    ],
    dos: [
      "Clear, sortable headers; legible density.",
      "Selection + bulk actions when applicable.",
      "Always handle loading, empty and error.",
    ],
    donts: [
      "Don't hide the total count or pagination.",
      "Don't use a table for 2–3 visual items.",
      "Don't leave the empty state without an exit (offer an action).",
    ],
  },
  "Components/Patterns/Form": {
    overview: "Form pattern: a surface with a title, optional banner, a single column of fields and an action footer on the right. For creating/editing entities, settings, checkout or onboarding.",
    whenToUse: [
      "Create or edit entities, settings, checkout, onboarding.",
      "Capture several related inputs in one view.",
    ],
    whenNotToUse: [
      "A single decision → use a dialog (Modal).",
      "Filters → inline controls without a “save”.",
    ],
    anatomy: [
      "Header — title (Title/L) + description.",
      "Banner — error summary (tone danger), optional.",
      "Fields — one column; short pairs in 2 columns (category + date).",
      "Actions — in the footer, on the right: primary (Create) + secondary (Cancel).",
    ],
    accessibility: [
      "Every control has an associated label (htmlFor/id) always visible above it.",
      "The error replaces the helper, as text + aria-invalid (not color alone).",
      "Full keyboard support and visible focus; preserve entered input on an error.",
    ],
    dos: [
      "Group related fields; ask only for what's necessary.",
      "Validate on submit and on blur, not on every keystroke.",
      "Clear, actionable messages (“Name is required”).",
    ],
    donts: [
      "Don't disable the primary because of errors: show them on attempt.",
      "Don't use codes or jargon in messages.",
      "Don't put everything in one wide row; one column except for short pairs.",
    ],
  },
  "Components/Patterns/Wizard": {
    overview: "Multi-step flow pattern: a Stepper marks progress, the current step is shown, and a footer with Back/Continue. For long or branching tasks.",
    whenToUse: [
      "Long or branching tasks — onboarding, initial setup, checkout, creating complex entities.",
      "When it helps to split a large goal into digestible steps.",
    ],
    whenNotToUse: [
      "Short tasks (a single-screen form).",
      "Non-linear flows where order doesn't matter.",
    ],
    anatomy: [
      "Stepper — completed steps (✓), the current one and the pending ones; numbered and labeled.",
      "Current step — the step's content (its title + fields).",
      "Footer — progress (“Step X of N”) + Back/Continue; the last step finishes.",
    ],
    accessibility: [
      "The stepper conveys progress with text and icon, not color alone.",
      "“Back” is always available except on the first step; completed steps are revisitable.",
      "Focus at the start of the new step; errors show on attempting to continue.",
    ],
    dos: [
      "Ideally 3–5 steps, one goal per step.",
      "Validate each step before advancing; preserve entered data when going back.",
      "The last step is a summary/confirmation before finishing.",
    ],
    donts: [
      "Don't show errors before the user tries to continue.",
      "Don't lose already-entered data when navigating between steps.",
      "Don't overdo the number of steps; on long flows, allow save and resume.",
    ],
  },
};
